# Generated by Django 4.1 on 2023-03-06 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("referrals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="referral",
            options={"verbose_name": "Referral", "verbose_name_plural": "Referrals"},
        ),
    ]
