# Generated by Django 4.1 on 2023-03-08 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("referrals", "0002_alter_referral_child_alter_referral_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child",
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="parent",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
