# Generated by Django 4.1 on 2023-03-06 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("referrals", "0002_alter_referral_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referral",
            name="referral_code",
        ),
    ]
