# Generated by Django 4.1 on 2023-03-07 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        default="Token",
                        max_length=50,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="Цена"
                    ),
                ),
                (
                    "total_amount",
                    models.PositiveIntegerField(verbose_name="Осталось токенов"),
                ),
                (
                    "total_sold",
                    models.PositiveIntegerField(verbose_name="Продано токенов"),
                ),
            ],
            options={
                "verbose_name": "Token",
                "verbose_name_plural": "Tokens",
            },
        ),
        migrations.CreateModel(
            name="TokenRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("$", "USD")],
                        default="$",
                        max_length=5,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=6, verbose_name="Цена"
                    ),
                ),
                ("total_cost", models.PositiveIntegerField(verbose_name="Цена за все")),
                (
                    "percent_share",
                    models.PositiveSmallIntegerField(verbose_name="Доля"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активен"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Завершен"),
                ),
            ],
            options={
                "verbose_name": "TokenRound",
                "verbose_name_plural": "TokenRounds",
                "ordering": ["-unit_price"],
            },
        ),
        migrations.CreateModel(
            name="TokenPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TokenPurchase",
                "verbose_name_plural": "TokenPurchases",
                "ordering": ["-created_at"],
            },
        ),
    ]
