# Generated by Django 4.1 on 2023-03-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="total_amount",
            field=models.PositiveBigIntegerField(verbose_name="Осталось токенов"),
        ),
        migrations.AlterField(
            model_name="token",
            name="total_amount_sold",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="Продано токенов"
            ),
        ),
    ]
