# Generated by Django 4.1 on 2023-03-07 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tokenpurchase",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Token Purchase",
                "verbose_name_plural": "Token Purchases",
            },
        ),
        migrations.AlterModelOptions(
            name="tokenround",
            options={
                "ordering": ["-unit_price"],
                "verbose_name": "Token Round",
                "verbose_name_plural": "Token Rounds",
            },
        ),
    ]
