# Generated by Django 4.1 on 2023-03-07 08:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0002_alter_tokenpurchase_options_alter_tokenround_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tokenround",
            options={
                "ordering": ["unit_price"],
                "verbose_name": "Token Round",
                "verbose_name_plural": "Token Rounds",
            },
        ),
    ]
