# Generated by Django 4.1 on 2023-03-09 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0002_alter_token_total_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenPurchase",
            fields=[],
            options={
                "verbose_name": "Token Purchase",
                "verbose_name_plural": "Token Purchases",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tokens.tokenorder",),
        ),
        migrations.CreateModel(
            name="TokenReward",
            fields=[],
            options={
                "verbose_name": "Token Reward",
                "verbose_name_plural": "Token Rewards",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tokens.tokenorder",),
        ),
        migrations.AddField(
            model_name="tokenorder",
            name="reward_sent",
            field=models.BooleanField(default=False, verbose_name="Награда начислена"),
        ),
        migrations.AlterField(
            model_name="tokenorder",
            name="token_round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="token_orders",
                to="tokens.tokenround",
            ),
        ),
    ]
