# Generated by Django 4.1 on 2023-03-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0003_alter_tokenround_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tokenround",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
