# Generated by Django 4.1 on 2023-03-09 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0003_tokenpurchase_tokenreward_tokenorder_reward_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenround",
            name="name",
            field=models.CharField(
                default="Раунд", max_length=50, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="active_round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tokens.tokenround",
                verbose_name="Активный раунд",
            ),
        ),
    ]
