# Generated by Django 4.1 on 2023-03-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0004_tokenround_name_alter_token_active_round"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenround",
            name="total_amount_sold",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Продано в раунде"
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="total_amount",
            field=models.PositiveBigIntegerField(verbose_name="Всего токенов"),
        ),
    ]
