# Generated by Django 4.1 on 2023-03-09 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tokens", "0005_tokenround_total_amount_sold_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenorder",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Покупатель",
            ),
        ),
        migrations.AlterField(
            model_name="tokenorder",
            name="token_round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="token_orders",
                to="tokens.tokenround",
                verbose_name="Раунд",
            ),
        ),
    ]
