# Generated by Django 4.1 on 2023-03-07 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0005_token_active_round"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="token",
            name="active_round",
        ),
    ]
