# Generated by Django 4.1 on 2023-03-07 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0006_remove_token_active_round"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="active_round",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="tokens.tokenround",
            ),
            preserve_default=False,
        ),
    ]
