# Generated by Django 4.1 on 2023-03-07 09:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0007_token_active_round"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="token",
            name="unit_price",
        ),
    ]
