# Generated by Django 4.1 on 2023-03-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0008_remove_token_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="total_sold",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Продано токенов"
            ),
        ),
    ]
