# Generated by Django 4.1 on 2023-03-07 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0009_alter_token_total_sold"),
    ]

    operations = [
        migrations.RenameField(
            model_name="token",
            old_name="total_sold",
            new_name="total_amount_sold",
        ),
    ]
