# Generated by Django 4.1 on 2023-03-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0010_rename_total_sold_token_total_amount_sold"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tokenpurchase",
            name="total_cost",
        ),
        migrations.AddField(
            model_name="tokenpurchase",
            name="unit_price",
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
