# Generated by Django 4.1 on 2023-03-08 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("referrals", "0003_alter_referral_referrer"),
        ("tokens", "0011_remove_tokenpurchase_total_cost_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Purchase", "Purchase"), ("Reward", "Reward")],
                        default="Purchase",
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="Количество")),
                (
                    "reward",
                    models.PositiveIntegerField(blank=True, verbose_name="Награда"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "buyer_parent",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="referrals.referral",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token Order",
                "verbose_name_plural": "Token Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameField(
            model_name="tokenround",
            old_name="is_completed",
            new_name="is_complete",
        ),
        migrations.DeleteModel(
            name="TokenPurchase",
        ),
        migrations.AddField(
            model_name="tokenorder",
            name="token_round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="tokens.tokenround"
            ),
        ),
    ]
