# Generated by Django 4.1 on 2023-03-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0012_tokenorder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenorder",
            name="reward",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Награда"
            ),
        ),
    ]
