# Generated by Django 4.1 on 2023-02-19 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customer_seller_user_is_customer_user_is_seller_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatars/default.png", upload_to="avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_customer",
            field=models.BooleanField(default=False, verbose_name="Покупатель"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_seller",
            field=models.BooleanField(default=False, verbose_name="Продавец"),
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("CUSTOMER", "customer"),
                    ("SELLER", "seller"),
                    ("BOTH", "both"),
                ],
                default="CUSTOMER",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("EN", "EN"), ("RU", "RU")], default="EN", max_length=3
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
