# Generated by Django 4.1 on 2023-02-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_avatar_alter_user_is_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("EN", "EN"), ("RU", "RU")], default="EN", max_length=3
            ),
        ),
        migrations.DeleteModel(
            name="UserSettings",
        ),
    ]
