# Generated by Django 4.1 on 2023-03-06 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_avatar_alter_user_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_code",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=150, unique=True
            ),
            preserve_default=False,
        ),
    ]
