# Generated by Django 4.1 on 2023-02-25 13:31

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="metamask_wallet",
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Phone number must be in the format "+999 999-9999".',
                        regex="^\\+?\\d{1,3}[\\d\\s-]{5,}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
    ]
