# Generated by Django 4.1 on 2023-02-25 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=25,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Phone number must be in the format "+999 999-9999".',
                        regex="^\\+?\\d{1,3}[\\d\\s-]{5,}$",
                    )
                ],
                verbose_name="Номер телефона",
            ),
        ),
    ]
