# Generated by Django 4.1 on 2023-03-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="metamask_confirmed",
            field=models.BooleanField(
                default=False, verbose_name="Metamask подтвержден"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="token_balance",
            field=models.PositiveIntegerField(default=0, verbose_name="Баланс токенов"),
        ),
    ]
